# Choose backend: sqlite or mysql
[db]
backend = "sqlite" # or "mysql"

[db.sqlite]
path = "./resilience.db"

[db.mysql]
host = "localhost"
port = 3306
user = "resilience_user"
password = "your_password_here"
database = "resilience"

[app]
title = "Operational Resilience Maturity Assessment"
